export const appRoute = {
    HOME : "/",
    ABOUT : "/about",
    CONTACT : "/contactus",
    WOMEN : "/women",
    SHOP : "/shop",
    ADMIN : "/admin",
    USER : "/user",
    CART : "/cart",
    EVERYTHINGS : "/everythings",
    MEN : "/men",
    ACCESSORIES : "/accessories",
    REGISTER: "/user/register",
    SINGLEPRODUCT : "/products/[id]",
    ADMINDASHBOARD : "/admin/dashboard",
    ALLUSER : "/admin/dashboard/alluser",
    ADMINPROFILE : "/admin/dashboard/profile",
    ADMINSETTING : "/admin/dashboard/setting",
    ADDPRODUCT : "/admin/dashboard/addproduct",
    USERDASHBOARD : "/user/dashboard",
    USERPROFILE : "/user/dashboard/profile",
    USERCHANGEPASSWORD : "/user/dashboard/changepassword",
    USERLOGOUT : "/user/dashboard/logout"
}